### ISSUE TITLE
implement automated activity points expiration

### ISSUE THREAD

**Issue by tomlibert8** [swissDAO/daotic#30]
- [x] update all functions which increase XPs to simultaneously increase activity points
- [x] create function "burnActivityPoints" which goes through all members and burns one activity point of them
- [x] using the ERC1155's function _burn(address from, uint256 id, uint256 value), the id of activity points is "1".
- [x] the function can use the ERC1155's mapping from token ID to account balances "_balances" to go through all members who own activity points
- [x] if(_balances[2][member]>0) does not have to be checked as it is automatically handled in the ERC1155.
- [x] this function is intended to be executed once a week by externally calling it.

**Comment by tomlibert8** [comment]
Good idea to add the timestamp difference condition! Someone/something still has to call the function, right?

**Comment by owieth** [comment]
> Good idea to add the timestamp difference condition! Someone/something still has to call the function, right?

I'm not 100% sure maybe we can have a small project to verify that flow?
